[workspace]
members = ["crates/*"]
resolver = "3"

[workspace.dependencies]
winit = { version = "0.30.9", features = ["rwh_05"] }
native-dialog = "0.7.0"
pollster = "0.4.0"
rand = "0.9.0"
thiserror = "2.0.12"
serde = { version = "1.0.219", features = ["derive"] }
