[package]
name = "vector-logging"
version = "0.1.0"
edition = "2024"

[dependencies]
thiserror = "2.0.12"
native-dialog = { workspace = true }
winit = { workspace = true }
utils = { package = "vector-utils", path = "../utils" }
